import { Item } from "./Item";

export class Person {
  public isProtagonist: boolean;
  public group: string;
  public name: string;
  public physical: number;
  public agility: number;
  public accuracy: number;
  public intelligence: number;
  public combatExperience: number;
  public travellingExperience: number;
  public doctor: number;
  public vetenary: number;
  public mechanic: number;
  public hunting: number;
  public collecting: number;
  public firstAid: number;
  public smuggling: number;
  public rangedWeapons: number;
  public closeCombat: number;
  public unarmed: number;
  public throwing: number;
  public crossbows: number;
  public pistols: number;
  public rifles: number;
  public machineGuns: number;
  public SMGs: number;
  public shotguns: number;
  public rocketLaunchers: number;
  public flamethrowers: number;
  public knives: number;
  public clubs: number;
  public choppingMelee: number;
  public swords: number;
  public dodge: number;
  public hpMax: number;
  public hp: number;
  public foodMorale: number;
  public waterMorale: number;
  public victoryMorale: number;
  public freedomMorale: number;
  public salaryMorale: number;
  public caloriesConsumption: number;
  public waterConsumption: number;
  public faction: string;
  public equipment: {
    weapon: Item;
    attachment1: Item;
    attachment2: Item;
    defaultAmmo: Item;
    secondaryWeapon: Item;
    secondaryAttachment1: Item;
    secondaryAttachment2: Item;
    secondaryDefaultAmmo: Item;
    inventory: Item[];
    helmet: Item;
    chestProtection: Item;
  };
  public distanceTravelled: number;
  public damageTaken: number;
  public hasDamagedEye: boolean;
  public hasDamagedLeg: boolean;
  public hasDamagedArm: boolean;
  public estPrice: number;
  public sight: number;
  public weight: number;
  public idealWeight: number;

  public getMaxLoad = () => {};
  public getSight = () => {};
  public getTotalExperience = () => {};
  public getLearningCapacity = () => {};
  public getPainThreshold = () => {};
  public reload = () => {};
  public getDodgeChance = () => {};
  public getHitChance = () => {};
  public attack = () => {};
  public move = () => {};
  public switchWeapons = () => {};
  public maxLoad = () => {};
  public getSightDistance = () => {};
  public getAP = () => {};
  public getMorale = () => {};
  public getHealthState = () => {};
  public getSpeed = () => {};
  public getPercentIdealWeight = () => {};
  public getDamageResistance = () => {};
  public getFireResistance = () => {};
  public getExplosionResistance = () => {};
}
